import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { AuthProvider } from "@/contexts/AuthContext";
import { ListingsProvider } from "@/contexts/ListingsContext";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { EmailVerificationBanner } from "@/components/email-verification-banner";
import { LanguageSwitcher } from "@/components/ui/language-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="light dark" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ListingsProvider>
            <LanguageProvider>
              <EmailVerificationBanner />
              <Header />
              {/* Language Switcher - Fixed in top right corner */}
              <div className="fixed top-4 right-4 z-[100] md:top-6 md:right-6">
                <LanguageSwitcher />
              </div>
          <script
            dangerouslySetInnerHTML={{
              __html: `
                (function() {
                  try {
                    var root = document.documentElement;
                    var mql = window.matchMedia('(prefers-color-scheme: dark)');
                    var KEY = 'theme:preference'; // new key to avoid legacy overrides
                    var stored = localStorage.getItem(KEY); // 'light' | 'dark' | 'system' | null
                    // One-time migration: if explicitly 'system' in old key, carry over; otherwise ignore
                    if (!stored) {
                      var legacy = localStorage.getItem('theme');
                      if (legacy === 'system') {
                        try { localStorage.setItem(KEY, 'system'); } catch {}
                        stored = 'system';
                      }
                    }

                    function apply(theme) {
                      var useDark = theme === 'dark' || (theme !== 'light' && mql.matches);
                      if (useDark) root.classList.add('dark');
                      else root.classList.remove('dark');
                    }

                    apply(stored);

                    // Keep in sync with OS when following system
                    try {
                      mql.addEventListener('change', function() {
                        var current = localStorage.getItem(KEY);
                        if (!current || current === 'system') apply(current);
                      });
                    } catch (_) {
                      // Safari fallback
                      mql.addListener(function() {
                        var current = localStorage.getItem(KEY);
                        if (!current || current === 'system') apply(current);
                      });
                    }
                  } catch (e) {
                    // no-op
                  }
                })();
              `,
            }}
          />
          <div className="flex min-h-screen flex-col">
            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </div>
            </LanguageProvider>
          </ListingsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
